### ISSUE TITLE
Interface db entry gets created despite related sql constraint violation

### ISSUE THREAD

**Issue by Metallion** [axsh/openvnet#261]
I used the following command to create an interface:

    ./vnctl interfaces add --uuid if-dhcp2 --mac-address 02:00:00:00:01:04 --network-uuid nw-vnet2 --ipv4-address 10.0.0.3 --mode simulated

It threw back the following error at me.

    :error: Sequel::UniqueConstraintViolation
    :message: 'Mysql2::Error: Duplicate entry ''2199023255810-0'' for key ''mac_address'''
    :code: 500

So obviously the mac address entry could not be created but the interface entry was still in the database.

We should use Sequel transactions so the whole thing can be rolled back in a case such as this.

**Comment by rakshasa** [comment]
This has already been fixed.
