### ISSUE TITLE
インストールガイドのテスト環境についての確認

### ISSUE THREAD

**Issue by userlocalhost2000** [axsh/openvnet#264]
こんにちわ。Ubuntu14.04 環境で OpenVNet のセットアップを実施しております。

以下インストールガイドに記述されております、テスト環境 (test environment) について確認させてください。
https://github.com/axsh/openvnet/blob/master/docs/InstallGuide.md

上記インストールガイド "Download test environment" の下記リンクからテスト環境をダウンロードし、
http://dlc.openvnet.axsh.jp/tests/vnet-test-kvm.tgz

ガイドに従い db.sh を実行したところ webapi.log で以下のエラーが出ます。
https://gist.github.com/userlocalhost2000/980cd3f175e40b728658

調べた所、以下のリクエスト実行時に上記のエラーが出力されている模様です。
```
curl -s -X POST --data-urlencode network_uuid=nw-public --data-urlencode broadcast_mac_address=08:00:27:10:03:01 http://${webapi_host}:${port}/api/datapaths/dp-node1/networks/nw-public
curl -s -X POST --data-urlencode network_uuid=nw-vnet1 --data-urlencode broadcast_mac_address=08:00:27:10:01:01 http://${webapi_host}:${port}/api/datapaths/dp-node1/networks/nw-vnet1
curl -s -X POST --data-urlencode network_uuid=nw-vnet2 --data-urlencode broadcast_mac_address=08:00:27:10:02:01 http://${webapi_host}:${port}/api/datapaths/dp-node1/networks/nw-vnet2
```

こちら、以下の通り interface_uuid パラメータを要求していますが、上記リクエストではこれの指定が無いためにエラーになっているものと思われます。
https://github.com/axsh/openvnet/blob/master/vnet/lib/vnet/endpoints/1.0/datapaths.rb#L43

もし、以下リンクのテスト環境が古いようでしたら最新のリンクを教えていただけますでしょうか。
http://dlc.openvnet.axsh.jp/tests/vnet-test-kvm.tgz

**Comment by Metallion** [comment]
Closing since the conversation has ended. Documentation updates are planned for the [0.7 milestone](https://github.com/axsh/openvnet/milestones/v0.7).
