### ISSUE TITLE
Flows are missing on vnet_edge

### ISSUE THREAD

**Issue by akry** [axsh/openvnet#282]
Flows including `mod_vlan_vid` are somehow not installed on vnet_edge. I suppose it's due to using the old version of trema.

https://github.com/axsh/openvnet/blob/master/vnet/lib/vnet/core/translations/vnet_edge_handler.rb#L196-L203
https://github.com/axsh/openvnet/blob/master/vnet/lib/vnet/core/translations/vnet_edge_handler.rb#L130-L135

**Comment by Metallion** [comment]
Do you think fixing these flows will get the edge test green?

**Comment by akry** [comment]
yes

**Comment by Metallion** [comment]
And this has been fixed. :) https://github.com/axsh/openvnet/pull/321

It is not quire yet the correct fix since we are using ovs-vsctl instead of OpenFlow but it makes vnet edge work again. We'll track the ovs-vsctl Vs. OpenFlow problem in a new issue.
