### ISSUE TITLE
Create a development yum repository

### ISSUE THREAD

**Issue by Metallion** [axsh/openvnet#296]
### Problem

Currently we have only two yum repositories.

* openvnet
* openvnet-third-party

They contain the RPMs from the master branch. From now master will contain only the stable numbered release. We should have another yum repository that contains the RPMs from the latest development branch.

### Solution

Make new yum repositories called `openvnet-development` and  `openvnet-third-party-development` which are hosted alongside the current repository based on master. That makes 4 repositories.

**The stable release**

* openvnet
* openvnet-third-party

**The development release**

* openvnet-development
* openvnet-third-party-development

**Comment by Metallion** [comment]
Currently the repository files are stored in OpenVNet's root directory. I think we should change it to the following directory tree.

```
openvnet
├── deployment
├── docs
├── vnet
├── vnctl
└── yum_repositories
    ├── development
    │   ├── openvnet.repo
    │   └── openvnet-third-party.repo
    └── stable
        ├── openvnet.repo
        └── openvnet-third-party.repo
```

**Comment by Mopster** [comment]
See : https://github.com/axsh/openvnet/pull/324

At the moment there isn't a dev release for the third party repo
