### ISSUE TITLE
Jenkins isn't reporting the integration test's result on pull requests

### ISSUE THREAD

**Issue by Metallion** [axsh/openvnet#297]
### Problem

After the integration test has run on a pull request, the report from jenkins (and axsh-bot) still list it as pending. The test itself works fine but only the reporting is broken.

### Solution

Currently it isn't known what's causing this but it's probably a simple setting somewhere in Jenkins. This just needs to be investigated and fixed when there is some time.

**Comment by hansode** [comment]
Configured some params. Wating for good results now.

**Comment by hansode** [comment]
for example: https://github.com/axsh/openvnet/pull/290

![fix vnctl command crash with early api calling by mopster pull request 290 axsh openvnet](https://cloud.githubusercontent.com/assets/76867/7384914/be00a636-ee76-11e4-94e6-2c483f9e5585.png)

**Comment by hansode** [comment]
![openvnet integration test config jenkins](https://cloud.githubusercontent.com/assets/76867/7384920/d79166e4-ee76-11e4-9261-1c11268dc813.png)

**Comment by hansode** [comment]
`Stable` -> `Failed`

![openvnet integration test config jenkins](https://cloud.githubusercontent.com/assets/76867/7384934/1d51a4e6-ee77-11e4-9f3c-eff7685cf96f.png)

**Comment by hansode** [comment]
Run a smoke test.

**Comment by hansode** [comment]
![fix vnctl command crash with early api calling by mopster pull request 290 axsh openvnet](https://cloud.githubusercontent.com/assets/76867/7385146/f7d8b250-ee7a-11e4-911d-2107e5e869c7.png)

**Comment by hansode** [comment]
@Metallion I fixed this issue. check please.

**Comment by Metallion** [comment]
Thank you very much, kind sir. :)
