### ISSUE TITLE
Router p2v integration test race condition

### ISSUE THREAD

**Issue by Metallion** [axsh/openvnet#300]
### Problem

When running the integration test on the same branch multiple times, the `router p2v` test will some times come up red and some times come up green. This race condition needs to be fixed.

### Solution

It is currently not known yet what causes this race condition. It needs to be investigated.

**Comment by triggers** [comment]
FYI, the log files (and much of the environment) from the vnet-bootstrap demo on November 12th are still on 192.168.2.24.
There may be some clues in there.  Test copies 1 and 6 failed.  2,3,4, and 5 passed.  Something strange happend on test copy 7, so probably best to ignore it.

```
/ssh:p24: #$ cd /home/triggers/vnet-october/demo/
/ssh:p24: #$ 
/ssh:p24: #$ grep '7 examples' ./copy*/test.log -A 5
./copy1/test.log:7 examples, 2 failures
./copy1/test.log-
./copy1/test.log-Failed examples:
./copy1/test.log-
./copy1/test.log-rspec ./spec/router_p2v_spec.rb:21 # router_p2v pnet tunnel reachable to vnet
./copy1/test.log-rspec ./spec/router_p2v_spec.rb:44 # router_p2v vnet tunnel reachable to pnet
--
./copy2/test.log:7 examples, 0 failures
./copy2/test.log-
./copy2/test.log-result: success
./copy2/test.log-Wed Nov 12 16:01:24 JST 2014,,,,,,,,,,,,,,,,,,,,,,,,,,,,
--
./copy3/test.log:7 examples, 0 failures
./copy3/test.log-
./copy3/test.log-result: success
./copy3/test.log-Wed Nov 12 16:01:23 JST 2014,,,,,,,,,,,,,,,,,,,,,,,,,,,,
--
./copy4/test.log:7 examples, 0 failures
./copy4/test.log-
./copy4/test.log-result: success
./copy4/test.log-Wed Nov 12 16:01:22 JST 2014,,,,,,,,,,,,,,,,,,,,,,,,,,,,
--
./copy5/test.log:7 examples, 0 failures
./copy5/test.log-
./copy5/test.log-result: success
./copy5/test.log-Wed Nov 12 16:01:10 JST 2014,,,,,,,,,,,,,,,,,,,,,,,,,,,,
--
./copy6/test.log:7 examples, 2 failures
./copy6/test.log-
./copy6/test.log-Failed examples:
./copy6/test.log-
./copy6/test.log-rspec ./spec/router_p2v_spec.rb:21 # router_p2v pnet tunnel reachable to vnet
./copy6/test.log-rspec ./spec/router_p2v_spec.rb:44 # router_p2v vnet tunnel reachable to pnet
--
./copy7/test.log:7 examples, 6 failures
./copy7/test.log-
./copy7/test.log-Failed examples:
./copy7/test.log-
./copy7/test.log-rspec ./spec/router_p2v_spec.rb:12 # router_p2v pnet mac2mac reachable to vnet
./copy7/test.log-rspec ./spec/router_p2v_spec.rb:21 # router_p2v pnet tunnel reachable to vnet
/ssh:p24: #$ 
```

**Comment by YamazakiYasuhiro** [comment]
Could you raise this to the highest priority?

**Comment by Mopster** [comment]
Problem has been located and linked to the initialization of the active_interface_manager before the datapaths have been initialized.

See : https://github.com/axsh/openvnet/blob/develop/vnet/lib/vnet/openflow/datapath.rb#L151

More information taken from HipChat : 
```
Jari Sundell: 

the TODO comment about blocking events is the most likely reason, and the lock should really be using celluloid's 'exclusive'

the latter is probably not the reason you have issues

we should probably have a way of blocking events and/or celluloid calls for all managers on a datapath until the initialization is done

...

regarding async... pretty much every place I use it, it is for a reason and shouldn't be changed.
unless the reason was 'brainfart'
or the code is really old

the exclusive block above makes no sense, is anything the whole method from checking if the datapath was added after termination, to where run_normal is called async.
terminate should also have a way of making sure the datapath it terminated has finished cleaning up before it starts initializing a new datapath, as the ovs-ofctl of both points to the same 'br123' bridge name
and the ovs datapath has the same dpid, so async / event processing on the terminating datapath might still be occuring
there is a celluloid actor shutdown handler that is used for some cleanup

BTW, setting/clearing the "@datapaths[dpid]" is atomic in the context of celluloid fibers, so adding a state to the datapaths hash seems the better solution
```

**Comment by Mopster** [comment]
What we've learned so far : 

Database does not hold any differences between failing and succeeding tests

All failing tests seem to be somehow related to the public interfaces. When a test fails, the test will always be a test originating from VM1/VM3 or have VM1/VM3 as the destination.

 10.102.0.0/24 : vm2, vm4 and vm6, 10.101.0.0/24 : vm5, public (172.16.90.0/24) : vm1 and vm3 

The errors are either : the physical network (vm1 and vm3) can't reach vm4 and/or vm6 inside the virtual network 10.102.0.0/24, strangly enough, vm2 inside the same virtual network has no problem. 

Strange stuff I tried : 

* Adding a sleep(10) between https://github.com/axsh/openvnet/blob/develop/vnet/lib/vnet/openflow/controller.rb#L130-L131 didn't change anything 
* Removing async everywhere, broke everything
* Removing async at specific locations didn't chang anything or made it worse
* adding 'datapath.wait_for_load_of_host_datapath' between https://github.com/axsh/openvnet/blob/develop/vnet/lib/vnet/openflow/controller.rb#L130-L131 also didn't work
* Adding code to add the datapath_info to all managers at https://github.com/axsh/openvnet/blob/develop/vnet/lib/vnet/openflow/datapath.rb#L102 aso did nothing : 
```
      @dp_info.managers.each { |manager|
        manager.set_datapath_info(@datapath_info)
      }
```
* Added an 'exclusive do' to https://github.com/axsh/openvnet/blob/develop/vnet/lib/vnet/openflow/controller.rb#L130 but that broke everthing

After running the tests, I restarted VNA, after restarting and checking the vnflows, the flows for the active interfaces are missing.

**Comment by Metallion** [comment]
This should get fixed by implementing https://github.com/axsh/openvnet/issues/356.

**Comment by rakshasa** [comment]
Looks like it has been fixed.
