### ISSUE TITLE
Master RPM packages should have version numbers

### ISSUE THREAD

**Issue by Metallion** [axsh/openvnet#314]
### Problem

Up until now, we didn't have version numbers and just released RPM packages on every commit to master. These RPM packages have the git commit id in their file name. Now that master is going to hold our stable releases, they should have version numbers instead.

### Solution

* RPMbuilds for master should still automatically run for every commit.
* Instead of git commit id, they should have the correct version number. *Every* commit to master will have a new version number.
* It needs to be decided where the RPMbuild code will read the version number. ~~Perhaps we should have a file named `VERSION` in the root directory that contains just the version number?~~

**Comment by Mopster** [comment]
See : https://github.com/axsh/openvnet/pull/316

**Comment by Metallion** [comment]
This is how we plan to do it right now.

**Workflow:**

1) Merge develop (or a release candidate if there is one) into Master.
2) Tag master with the correct version number.
3) Run the **release_stable_rpm** jenkins job

New jenkins job: **release_stable_rpm**

* This Jenkins job will take a parameter `RPM_VERSION` in which we fill in the version tag. For example `v0.7`

* The job will do a `git checkout ${RPM_VERSION}`. Since we have merged to mater and tagged it with `v0.7`, it will check out the correct tag.

* The job will build RPMS from that version and then upload them to our *stable* repository.

**Comment by Mopster** [comment]
Current situation (after changes) : 

Code changes : 

* In build_packages_vnet.sh script : renamed 'build_time' to 'rpm_suffix', when no 'RPM_SUFFIX' variable is given, a timestamp will be used
* 'version' in the OpenVNet recipe's will now contain RPM_SUFFIX or a timestamp

CI changes

* A new job called 'vnet.stable-release.rpmbuild6' has been created. This job has to be started manually. The variable 'GIT_BRANCH' and 'RPM_VERSION' have to be specified before starting the job. Both parameters should contain the annotated version tag. (for example: v0.7).
* The 'vnet.stable-release.rpmbuild6' job will trigger another new job called 'vnet.stable-release.release-package6', which will upload the generated RPM's from the previous job on Amazon S3
* A new managed script on jenkins has been created to deal with a release_id format change, script is called 'vnet.stable-release.rpmbuild6.to-s3'

Next question : 

Currently the RPM's are being uploaded to : 

s3://dlc.openvnet.axsh.jp/packages/rhel/6/vnet/'''$GIT_BRANCH'''/current/x86_64/openvnet-common-rel_test_version.fpm0-1.x86_64.rpm

Which results in a new folder for every new tag.

My suggestion would be to change the folder to : 

s3://dlc.openvnet.axsh.jp/packages/rhel/6/vnet/'''stable-release'''/current/x86_64/openvnet-common-rel_test_version.fpm0-1.x86_64.rpm

So all stable releases can be found in : 

s3://dlc.openvnet.axsh.jp/packages/rhel/6/vnet/'''stable-release'''/

**Comment by Metallion** [comment]
Done.
