### ISSUE TITLE
host/edge port refactor

### ISSUE THREAD

**Issue by akry** [axsh/openvnet#322]
### Problem

The current implementation of vnet_edge requires 2 types of devices (host and edge) and those devices are needed to be promiscuous mode. This is not favourable design because the promiscuous mode is strictly prohibited on some environments. On those environment any tunnelling port is ideally be used as host/edge port. However there is no way to specify tunnelling port as host/edge port in the current design because those ports are automatically created at runtime.

**Comment by akry** [comment]
workaround:

Create another datapath (hereafter tunnel datapath) only for aggregating tunnelling port. Cascade the main datapath to the tunnel datapath with patch port. Register the patch port in host/edge mode in the database.

**Comment by akry** [comment]
To be honest this is not a bug but expected feature. The host/edge port design should be more flexible for ease of installation under some circumstances. I could label this as Type:Feature.

**Comment by Metallion** [comment]
I think the correct type for this is code enhancement

**Comment by rakshasa** [comment]
VNetEdge is no more.
