### ISSUE TITLE
Automate mac2mac broadcast address assignment for datapath network

### ISSUE THREAD

**Issue by unakatsuo** [axsh/openvnet#327]
WebAPI and ``vnctl`` require ``broadcast_mac_address`` parameter mandatory. The beginner user will have difficulty to understand the address convention in terms of its uniqueness.  The address generation can be automated.

Behavior Changes:

+ ``broadcast_mac_address`` parameter is kept as it is but changed to an optional parameter. for WebAPI and ``vnctl datapaths networks``
+ WebAPI will set appropriate address to the field if none of the parameter.

**Comment by Metallion** [comment]
I think it is not the WebAPI's responsibility to set the appropriate address, or at least it shouldn't be written directly in the Sinatra route. Sinatra's only responsibility should be to provide a HTTP layer on top of more generalized ruby methods.

**Comment by rakshasa** [comment]
This issue has been discussed with Yokokawa-san and while I can't remember if anything was ever written down specifically, a design has been pretty much decided on.

Basically a mac lease policy similar to the ip lease policy needs to be added, and it will be used by nodeapi when creating a new broadcast_mac_address.

**Comment by rakshasa** [comment]
Already implemented.
