### ISSUE TITLE
Automate datapath network assginment while attaching VIF to a datapath.

### ISSUE THREAD

**Issue by unakatsuo** [axsh/openvnet#337]
VNet has a concept to relate datapath and virtual network 
but it is possible to hide the operations from user's normal operation.

Here the steps until attach VIF to datapath at this morment.

```
% vnctl networks add --ipv4-address=0.0.0.0  # (1)
% vnctl interfaces add --network-uuid=nw-xxxxx --mac-address=xx:xx:xx  # (2)
% vnctl datapaths add --dpid=0xffff  --node-id=vna.xx  # (3)
% vnctl datapath networks add nw-xxx --broadcast-mac-address=xx:xx:xx --interface-uuid=if-xxx  # (4)
# Then it's ready to attach if-xxx to OVS.
% ovs-dpctl add-if ovs1 tap1
```

The goal of this change is to make the 4th operation above optional. OpenVNet can support to apply same data model changes upon the openflow event after ``ovs-dpctl add-port ovs1 tap1``.

```
% vnctl datapath networks add nw-xxx --broadcast-mac-address=xx:xx:xx --interface-uuid=if-xxx
```

**Comment by rakshasa** [comment]
Topologies has been implemented.
