### ISSUE TITLE
Remove version folder in endpoints

### ISSUE THREAD

**Issue by Mopster** [axsh/openvnet#343]
The 1.0 folder should be removed from the endpoints folder. The code and version of the API should follow the version of the OpenVNet.

In case an older API version is needed, it would be good to have the older version running alongside the newer version. Because the same port is being used, a proxy could be used to redirect the request to the correct version based on the route of the request. 

```
/api/v1.0/... -> proxy -> v1.0 code
/api/v1.1/... -> proxy -> v1.1 code
/api/v2.0/... -> proxy -> v2.0 code
```

**Comment by Metallion** [comment]
I am in favour of dropping the version number but using `/api/<current_openvnet_version>/...` is not a good idea. That would mean the WebAPI url would change for every version, meaning every client has to be updated each time a new version is released.

**Comment by Metallion** [comment]
Currently not a priority.
