### ISSUE TITLE
Write documentation for integration test

### ISSUE THREAD

**Issue by Mopster** [axsh/openvnet#353]
Documentation needs to be written on the integration tests containing the requirements and instructions on how to use them.

* Requirements
* How to start a test
* List of available tests explaining what they test
* Instructions on how to expand (or customizing?) testing

Last point might be skipped if we're planning on rewriting the integration test suite (as discussed before).

**Comment by Metallion** [comment]
I think this a low priority *would-be-nice-to-have* feature as the integration test is mostly for internal use. We need more OpenVNet usage documentation first.

**Comment by Metallion** [comment]
Done.
