### ISSUE TITLE
Implement vnet-edge fix using OpenFlow instead of ovs-vsctl

### ISSUE THREAD

**Issue by Metallion** [axsh/openvnet#362]
### Problem

When using OpenFlow to implement vnet-edge, a couple of flows were not applied correctly. This seems to be a Trema issue but we are not sure yet how to fix it. In https://github.com/axsh/openvnet/issues/282 we have worked around the problem by calling `ovs-vsctl` directly.

### Solution

Investigate the Trema problem and use OpenFlow again instead of ovs-vsctl.

**Comment by rakshasa** [comment]
VNetEdge is no longer.
