### ISSUE TITLE
Add a new FilterManager

### ISSUE THREAD

**Issue by Metallion** [axsh/openvnet#364]
This is the first step of https://github.com/axsh/openvnet/issues/286's security group refactoring process.

We will implement a new manager called Filter2Manager that will apply very simple rules.

The following is taken from https://github.com/axsh/openvnet/issues/286#issuecomment-94826623.

* Implement a new filter manager.
  * Call it Filter2Manager until the old one is deprecated.
  * Use translation manager as a template.
  * Use TABLE_INTERFACE_INGRESS/EGRESS_FILTER.
  * Simple filtering rules mode (called static_filter/address mode?)
    * Each rule has a boolean for either drop of pass.
    * Each rule has two booleans for ingress and/or egress filtering.    
    * Each rule takes a prefix for address and port, 0/0 matches all.

**Comment by Metallion** [comment]
Some additional comments/suggestions:

* It should not respond to events. Other managers will call it directly.
* The calling managers will decide the cookies this manager's flows get.

* Currently the interfaces have a `ingress_filtering_enabled` flag in the database. Should it be this manager's responsibility to check whether or not that flag is set? I would assume so.

**Comment by rakshasa** [comment]
> * It should not respond to events. Other managers will call it directly.

Events are required to ensure only one of each :id is being processed at a time.

> * Currently the interfaces have a `ingress_filtering_enabled` flag in the database. Should it be this manager's responsibility to check whether or not that flag is set? I would assume so.

No, it needs to be in interface manager due to the way filtering is enabled in the flow table at the time the interface's flows are created.

**Comment by Metallion** [comment]
The vnctl commands for the new filter manager should be like this:

```
vnctl filters add
vnctl filters del
vnctl filters modify
vnctl filters show
vnctl filters static add
vnctl filters static del
```

**Comment by Metallion** [comment]
* filter_statics table need to get a flag `passthrough`
  - if 1: translate to ACCEPT for human readability
  - if 0: translate to DROP for human readability

**Comment by Metallion** [comment]
Done.
