### ISSUE TITLE
Active port manager

### ISSUE THREAD

**Issue by rakshasa** [axsh/openvnet#378]
To properly refactor port manager (#374) we need to add an active port manager that keeps track of active ports, and what interfaces they are associated with. This will include updates to the db when ports are added / removed.

Active port manager will be responsible for attempting to match ports to interface's and tunnels, and if unsuccessful mark them as 'unknown'.

Port manager will be moved to bootstrap managers in order to support implementation of a proper bootstrap mode.

**Comment by Metallion** [comment]
Done. https://github.com/axsh/openvnet/pull/422
