### ISSUE TITLE
Create tunnels when no host interface is enslaved

### ISSUE THREAD

**Issue by akry** [axsh/openvnet#398]
Current implementation totally relies on at least one host interface is enslaved to a datapath. When the vna detects a host interface through port_status event, it starts loading interface, datapath, datapath_network, then creates tunnels upon the network of src/dst interfaces.

It might happen that there is no host interface associated to a datapath. Under such circumstance tunnels are needed for all possible combinations of datapaths.

**Comment by rakshasa** [comment]
It shouldn't create tunnels in those cases, and the whole tunnel-related code will be redone at some later time.
