### ISSUE TITLE
Update Ruby to version 2.3.1

### ISSUE THREAD

**Issue by Metallion** [axsh/openvnet#400]
Currently we are still using Ruby 2.1.1. We should periodically update the new ruby versions. Right now ~~2.2.2~~ 2.3.1 is the latest so we should update to that.

**Comment by Metallion** [comment]
While we're at it, let's build with -O 0. (optimization 0)

**Comment by Metallion** [comment]
Unfortunately I don't remember why I made the optimization 0 comment and a quick google search didn't tell me. Anyway the solution should probably be two-fold.

- [ ] Confirm that OpenVNet works on Ruby 2.3.1. If there are problems, fix them. This could be done by installing 2.3.1 locally using rvm or rbenv.

- [ ] Update the `openvnet-ruby package` in the [develop third party yum repo](https://github.com/axsh/openvnet/blob/develop/deployment/yum_repositories/development/openvnet-third-party.repo).

    * Looking at the url, I see that the third party repository for stable and develop is point to the same place. When updating ruby, those will need to be separated. The stable repository should stay the same and the develop repository should be moved.

    * The current third party ruby package still uses fpm which we intend to phase out. If updating ruby is as simple as changing the version number in fpm and rebuilding, we could keep it for now but if it requires more work, it might be better to change it to an rpm spec.

**Comment by toros11** [comment]
After upgrade, this warning message sometimes shows up
 warning: circular argument reference -

**Comment by Metallion** [comment]
Done.
