### ISSUE TITLE
Update Open vSwitch to version 2.4.0

### ISSUE THREAD

**Issue by hansode** [axsh/openvnet#407]
### Background

+ ovs-2.4.0's openvswitch.rpm does not require kmod-openvswitch.
+ since cento-6.4 centos vanilla kernel includes openvswitch.ko

### Solution

+ update ovs to 2.4.0
+ remove kmod-openvswitch dependency

**Comment by Metallion** [comment]
2.5 has been released. A new issue needs to be made to update to that.
