### ISSUE TITLE
Static address translation should separate TCP and UDP

### ISSUE THREAD

**Issue by rakshasa** [axsh/openvnet#424]
Currently static_address translation creates both TCP and UDP flows when port translation is set. This should be changed to require a separate static_address entry for the two protocols.

**Comment by rakshasa** [comment]
In addition vnctl does not support adding/removing static_address rules.

**Comment by rakshasa** [comment]
The model should validate ip and port range and that both ports are either null or valid.

**Comment by Metallion** [comment]
These are 3 different issues and should be organized as such.
