### ISSUE TITLE
Add batch processing to vnctl

### ISSUE THREAD

**Issue by rakshasa** [axsh/openvnet#455]
The lack of batch/interactive processing in vnctl means that creating environments from scripts can take much longer than it should as vnctl must be executed for every single entry.

It should check if the first argument is e.g. '-b' before initializing Thor, and if so pass to Thor commands from stdin.

**Comment by Metallion** [comment]
Knowing Thor, it might be easier to implement using a subcommand instead of an argument. `vnctl batch`

What do we do when a command fails? A couple of ideas:

* Stop execution

* Continue execution and report errors later

* an argument to switch between behaviours.

**Comment by rakshasa** [comment]
Implemented.
