### ISSUE TITLE
Allow changes to the UUID after item deletion

### ISSUE THREAD

**Issue by rakshasa** [axsh/openvnet#490]
- Add options to pass on delete to decide if the uuid should be preserved or not.
- Allow options to be passed on POST to change any old uuid.
- Allow PUT modify to change the uuid on deleted items.
- Add configuration option that decides what to do for:
  - Collision on POST.
  - Default on DELETE.

**Comment by rakshasa** [comment]
When an old UUID is being replaced it should probably be configurable/optional choice between adding a random post/prefix or generate a new random uuid.

**Comment by Metallion** [comment]
Done.
